language: ruby
cache: bundler
rvm:
  - 2.3.1

branches:
  only:
    - master

install:
 - ./ci/setup

script:
 - ./ci/build

after_script:
 - git add -f _site
 - git rm -r ci _config.yml css Gemfile Gemfile.lock img _includes index.md _layouts README.md _sass
 - git commit -m "Released at `date +%s`"
 - git checkout -B release
 - git push -fu origin release:release
