language: ruby
cache: bundler
rvm:
  - 2.3.1

install:
 - ./ci/setup

script:
 - ./ci/build

after_script:
 - git co -B release
 - git add -f _site
 - git commit -m "Released at `date +%s`"
 - git push -fu origin release:release
