title: HTTPoxy
email: contact@httpoxy.org
description: >
  HTTPoxy is a vulnerability due to be disclosed in July 2016, affecting
  web applications.
baseurl: ""
url: "https://httpoxy.org"

markdown: kramdown

exclude:
  - ci/
  - vendor/
  - Gemfile
  - Gemfile.lockv

gems:
  - jekyll-assets
  - bootstrap
